name: Continuous Integration Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRASIL_API_URL: https://brasilapi.com.br/api/cep/v2/
      OSRM_API_URL: http://router.project-osrm.org/route/v1/driving/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev

      - name: Check Formatting
        run: |
          pipenv run black --check .

      - name: Lint Code
        run: |
          pipenv run ruff check .

      - name: Type Check
        run: |
          MYPYPATH=src pipenv run mypy -m main

      - name: Run tests with coverage
        run: |
          pipenv run pytest --cov=src --cov-fail-under=80
